export const API_BASE_URL = 'https://stage-api.ufs.com/auth';
export const SUBSCRIPTION_KEY = 'f6acb8e1cc574a41bbcc82e177524a9d';
export const COUNTRY_CODE = 'AU';
export const SITE_CODE = 'ufs-au';
export const LANGUAGE_CODE = 'en';

export const ENDPOINTS = {
  login: '/authenticate',
  register: '/register',
  logout: '/logout',
  resetPassword: '/request/resetPassword',
};

export const BUSINESS_TYPE_MAP = {
  'independent-restaurant': 'independent-restaurant',
  'chain-restaurant': 'chain-restaurant',
  hotel: 'hotel',
  catering: 'catering',
  other: 'other',
};

export function createRegistrationPayload(data) {
  const {
    email,
    password,
    confirmPassword,
    firstName,
    lastName,
    mobilePhone = '',
    marketingConsent = false,
    typeOfBusiness,
    now,
    referrerUrl,
    fullName,
    anonymousUserId,
  } = data;

  let idValue = 0;
  if (anonymousUserId) {
    const parsedId = parseInt(anonymousUserId, 10);
    if (!Number.isNaN(parsedId)) {
      idValue = parsedId;
    }
  }

  const payload = {
    id: idValue,
    ...(anonymousUserId ? { user_id: anonymousUserId } : {}),
    site: SITE_CODE,
    email,
    mobilePhone: mobilePhone ?? '',
    password,
    confirmPassword,
    phoneNumber: null,
    channelPreference: 'NOT_KNOWN',
    faxNumber: null,
    firstName,
    lastName,
    gender: null,
    integrationSourceName: null,
    title: null,
    countryCode: COUNTRY_CODE,
    languageCode: LANGUAGE_CODE,
    fbUserId: null,
    fbToken: null,
    numberOfCovers: null,
    numberOfLocations: null,
    numberOfKitchenStaff: null,
    businessName: null,
    state: null,
    houseNumber: null,
    houseNumberExtension: null,
    street: null,
    city: null,
    district: null,
    country: COUNTRY_CODE,
    zipCode: null,
    typeOfBusiness,
    typeOfCuisine: null,
    jobTitle: null,
    distributor: null,
    distributorEmail: null,
    website: null,
    webUpdaterId: null,
    numberOfCoversPerDay: null,
    distributorCustomerId: null,
    privateHousehold: null,
    oldPrivateHousehold: true,
    taxNumber: null,
    openOnMonday: null,
    openOnTuesday: null,
    openOnWednesday: null,
    openOnThursday: null,
    openOnFriday: null,
    openOnSaturday: null,
    openOnSunday: null,
    operatorRefId: null,
    confirmUrl: null,
    passwordMd5Hash: null,
    newsletterOptIn: marketingConsent,
    oldNewsletterOptIn: null,
    confirmedNewsletterOptIn: marketingConsent,
    updateNewsletterSubscription: true,
    newsletterConfirmUrl: null,
    accountOptIn: true,
    accountOptInConfirmed: null,
    enableNewsletterOptInWithConsent: null,
    trackingId: null,
    requestType: null,
    optInDate: now,
    confirmedOptIn: true,
    confirmedOptInDate: now,
    profileLoginType: 'EMAIL',
    promotionType: null,
    createdAt: now,
    consentOptIn: true,
    consentOptInDate: now,
    consentOptInConfirmed: true,
    consentOptInConfirmedDate: now,
    consentOptInForPromotions: null,
    consentOptInDateForPromotions: null,
    consentOptInConfirmedForPromotions: null,
    consentOptInConfirmedDateForPromotions: null,
    consentOptInForEventTraining: null,
    consentOptInDateForEventTraining: null,
    consentOptInConfirmedForEventTraining: null,
    consentOptInConfirmedDateForEventTraining: null,
    contactPersonRefId: null,
    ageVerified: null,
    termsAndAge: null,
    oldAgeVerified: null,
    ageVerifiedDate: null,
    thirdPartyConsent: null,
    oldThirdPartyConsent: null,
    granularConsentParentCheckbox: null,
    oldGranularConsentParentCheckbox: null,
    newsletterOptInForPromotions: null,
    newsletterOptInForEventTraining: null,
    confirmedNewsletterOptInForPromotions: null,
    confirmedNewsletterOptInForEventTraining: null,
    oldNewsletterOptInForPromotions: null,
    oldNewsletterOptInForEventTraining: null,
    termsAndConditions: null,
    termsAndConditionsDate: null,
    oldTermsAndConditions: null,
    clientId: 'a23h6lsLjXZOoljihm0t3i8xen0uhF4aMQdh6Aog',
    sourceName: 'EMAKINA',
    birthDate: null,
    dataAbroadOptin: null,
    kvkkConsent: null,
    consentToEmployer: null,
    distributorBranchName: null,
    averagePrice: null,
    referrerUrl,
    mobileOptIn: null,
    utmValue: null,
    utmSource: null,
    utmMedium: null,
    utmCampaign: null,
    utmTerm: null,
    utmContent: null,
    lineId: null,
    moduleType: null,
    journeyType: null,
    doubleOptInFlag: null,
    mobileOptInDate: now,
    enableCustomEventTrigger: false,
    mailRealTimeEvent: null,
    disableMailRealTimeEvent: false,
    contactFormTitle: null,
    validData: false,
    submittedPage: null,
    nextPage: null,
    processProfile: false,
    isUsed: false,
    address: '   ',
    fullName,
    distributorEmailArray: [],
    termsANDAge: null,
  };

  return payload;
}
